baseURL = 'https://plovski.dk/'
languageCode = 'en-us' # Retter sprogkode til engelsk, som du ønskede
title = 'Plovskis'
theme = 'PaperMod'

# Parametre nødvendige for PaperMod
[params]
    env = "production" # Helt nødvendigt for at temaet fungerer korrekt
    defaultTheme = "light" # Standard lyst tema
    disableThemeToggle = false # Tillader skift mellem lyst/mørkt tema
    ShowReadingTime = true # Viser estimeret læsetid
    
# Forside indstillinger
[params.homeInfoParams]
    Title = "Plovskis' hjemmeside"
    Content = "Welcome to my clean, static site built with Hugo and PaperMod."

# ... (resten af din konfiguration)

[params.assets]
    # Fortæl PaperMod, at den skal kombinere din custom.css med temaets egen stil
    customCss = true 
    
    # PaperMod's standard CSS vil blive kombineret med en fil, der hedder
    # assets/css/extended.css. Vi skal inkludere din custom.css i denne fil.

# Indstillinger for lister (f.eks. /posts)

[params.list]
    paginate = 5
    showPostNavHeaders = false

# MINIMALISTISK HOVEDMENU (Tilføj/erstat i bunden af hugo.toml)
[[menu.main]]
    identifier = "hjem"
    name = "Hjem"            
    url = "/posts/"          # PEGER PÅ DIN INDLÆGSOVERSIGT (Blog-listen)
    weight = 10              # Viser den først

[[menu.main]]
    identifier = "om mig"
    name = "Om Mig"
    url = "/pages/about-me/" # PEGER PÅ DIN ABOUT-ME SIDE
    weight = 20              # Viser den som nummer to

# yaml som default i front matter
metaDataFormat = "yaml" 
