# Simplified workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages (Simplified)

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Sørger for at kun ét deployment kører ad gangen
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code and Submodules
        uses: actions/checkout@v4
        with:
          submodules: true # Håndterer dit Ananke tema automatisk!
          fetch-depth: 0

      # Henter og installerer Hugo Extended
      - name: Setup Hugo Extended
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # Brug den nyeste version
          extended: true         # VIGTIGT: Sikrer Extended version til temaer/Sass

      - name: Build with Hugo
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
